package com.example.communityapp.models

enum class Nationality(val displayName: String) {
    AFGHAN("Afghan"),
    ALBANIAN("Albanian"),
    ANDORRAN("Andorran"),
    AUSTRIAN("Austrian"),
    BAHRAINI("Bahraini"),
    BELARUSIAN("Belarusian"),
    BELGIAN("Belgian"),
    BOSNIAN_HERZEGOVINIAN("Bosnian and Herzegovinian"),
    BULGARIAN("Bulgarian"),
    CROATIAN("Croatian"),
    CYPRIOT("Cypriot"),
    CZECH("Czech"),
    DANISH("Danish"),
    ESTONIAN("Estonian"),
    FINNISH("Finnish"),
    FRENCH("French"),
    GERMAN("German"),
    GREEK("Greek"),
    HUNGARIAN("Hungarian"),
    ICELANDIC("Icelandic"),
    IRANIAN("Iranian"),
    IRAQI("Iraqi"),
    IRISH("Irish"),
    ISRAELI("Israeli"),
    ITALIAN("Italian"),
    JORDANIAN("Jordanian"),
    KAZAKHSTANI("Kazakhstani"),
    KUWAITI("Kuwaiti"),
    KOSOVAR("Kosovar"),
    LATVIAN("Latvian"),
    LEBANESE("Lebanese"),
    LITHUANIAN("Lithuanian"),
    MALTESE("Maltese"),
    MOLDOVAN("Moldovan"),
    MONTENEGRIN("Montenegrin"),
    DUTCH("Dutch"),
    NORTH_MACEDONIAN("North Macedonian"),
    NORWEGIAN("Norwegian"),
    OMANI("Omani"),
    POLISH("Polish"),
    PORTUGUESE("Portuguese"),
    QATARI("Qatari"),
    ROMANIAN("Romanian"),
    RUSSIAN("Russian"),
    SAUDI_ARABIAN("Saudi Arabian"),
    SERBIAN("Serbian"),
    SLOVAK("Slovak"),
    SLOVENIAN("Slovenian"),
    SPANISH("Spanish"),
    SWEDISH("Swedish"),
    SWISS("Swiss"),
    SYRIAN("Syrian"),
    TURKISH("Turkish"),
    UKRAINIAN("Ukrainian"),
    EMIRATI("Emirati"),
    BRITISH("British"),
    YEMENI("Yemeni");
}
